### ISSUE TITLE
Distinguish non idenpotent requests?

### ISSUE THREAD

**Issue by nunogoncalves** [buzzfeed/MockDuck#20]
Hello, 

I was trying to make non idempotent requests work, but I'm having a bit of a hard time. 

Example: 

1 - get list of cart items - 0 items
2 - add one item to cart 
3 - get list of cart items - 1 items

I actually need the very same request to be saved multiple times because it might be different depending on server state.

My very fist idea was to create a custom MuckDuck delegate and have something like this:

```swift
// dictionary with the request and its index. this index would be appended to the 
// URL to make the hash different and therefore all requests to the same resource 
// would be saved in different files

// ex:
// api/users/1/chart = 0 -> file A
// api/users/1/chart = 1  -> file B
var requestIndex: [String: Int] = [:]  

class SampleMockDuckDelegate: MockDuckDelegate {

    func normalizedRequest(for request: URLRequest) -> URLRequest {

        guard let url = request.url else { return request }
        let urlString = url.absoluteString

        if let i = requestIndex[urlString] {
            requestIndex[urlString] = i + 1
        } else {
            requestIndex[urlString] = 1
        }

        var urlComponents = URLComponents(url: url, resolvingAgainstBaseURL: true)!
        var items = urlComponents.queryItems ?? []
        // update the url with the index of the request
        items.append(URLQueryItem(name: "mock-order", value: "\(requestIndex[urlString]!)"))
        urlComponents.queryItems = items

        var request = request
        request.url = urlComponents.url!

        return request
    }
}

```

For what I can see the `normalizedRequest(for:)` is called 3 times for a given request, and I end up having different hashes for the 2 files (`url-hash-response.json` and `url-hash.json`). 

Do you guys have any idea on how to accomplish this? Am I on the right path? Spending more time analysing this I'll probably have a better understanding on the library, but for now, maybe you guys already thought about this and have some suggestions. 
I would also gladly support the library if there's room for improvement on this front. 

Thanks for this library. I spent over a year thinking that the simulator has no access to the disk outside of the sandbox, and could only think about mock servers for this purpose. If this turns out to work for my use cases... damn will I be happy! 

Many thinks again.

**Comment by scelis** [comment]
This was handled in #26
