### ISSUE TITLE
Problem in recording and loading requests with non-empty body

### ISSUE THREAD

**Issue by abbasmousavi** [buzzfeed/MockDuck#23]
Sometimes it happens that `.httpBody` of a post request is empty, but `.httpBodyStream` contains the body of the request. In this case, when recording, the library will not save any `-request` file (because `.httpBody` is empty) but when loading it tries to load that file because the content type of the request is `application/json` and so the loading fails.

**Comment by abbasmousavi** [comment]
There is another related problem. The library uses the body of requests to generate the hash. If you serialize your native models to JSON and use it as the body of the request (which is a common use-case) the order of keys will be random, so the hash can be different when you record the request and when you try to load it. I know that this is the responsibility of the `normalizedURL` in the delegate to normalize the requests, but maybe we can find a solution for this inside the library

**Comment by scelis** [comment]
This sounds like a good candidate for a PR. Would you mind implementing this in its own PR when you have the chance? Thank you!

**Comment by abbasmousavi** [comment]
Yes, I will implement it in a different PR.

**Comment by scelis** [comment]
This has been fixed in #28
